// File generated by FlutterFire CLI
// Provides platform-specific Firebase configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can override this by passing a FirebaseOptions instance to '
          'Firebase.initializeApp',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can override this by passing a FirebaseOptions instance to '
          'Firebase.initializeApp',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBIUeMiB7_mHj_wqFsj9QggIp-UR9IfRmw",
    authDomain: "app-bound.firebaseapp.com",
    databaseURL: "https://app-bound-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "app-bound",
    storageBucket: "app-bound.firebasestorage.app",
    messagingSenderId: "826716620374",
    appId: "1:826716620374:web:04e6b2f1600daaf03d9df7",
    measurementId: "G-K425KWZL0E",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCYI18271f8dYn3aQMmgPdxQ1ariHz6TZU",
    authDomain: "app-bound.firebaseapp.com",
    databaseURL: "https://app-bound-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "app-bound",
    storageBucket: "app-bound.firebasestorage.app",
    messagingSenderId: "826716620374",
    appId: "1:826716620374:android:04e6b2f1600daaf03d9df7",
    measurementId: "G-K425KWZL0E",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCYI18271f8dYn3aQMmgPdxQ1ariHz6TZU",
    authDomain: "app-bound.firebaseapp.com",
    databaseURL: "https://app-bound-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "app-bound",
    storageBucket: "app-bound.firebasestorage.app",
    messagingSenderId: "826716620374",
    appId: "1:826716620374:ios:04e6b2f1600daaf03d9df7",
    measurementId: "G-K425KWZL0E",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyCYI18271f8dYn3aQMmgPdxQ1ariHz6TZU",
    authDomain: "app-bound.firebaseapp.com",
    databaseURL: "https://app-bound-default-rtdb.europe-west1.firebasedatabase.app",
    projectId: "app-bound",
    storageBucket: "app-bound.firebasestorage.app",
    messagingSenderId: "826716620374",
    appId: "1:826716620374:macos:04e6b2f1600daaf03d9df7",
    measurementId: "G-K425KWZL0E",
  );
}